### PR TITLE
Configure node modules base dir

### PR DESCRIPTION
**Pull request by rexsuecia**
Please just let me know if you want a different style of coding.

I opted for a new interface (in case there will be more configuration in the future). The default have sane backward compatible default. 

Added a tiny piece of config.

### CODE REVIEW

**Comment by jeremysmartt** [comment]
👍

**Comment by ScriptPup** [comment]
Is this ever going to make it into a release? I'm experiencing the exact same issue as described in 
https://github.com/Teradata/nodejs-driver/issues/15 and it looks like this is the fix - But it's been almost a year since this PR was made and it's still not even merged into main?

**Comment by adamtwo** [comment]
Hi all, I've recently joined Teradata as a dev advocate. Thanks for submitting a PR for this issue. I've been working with the nodejs driver to process this PR.  Sorry that it has taken so long to take action. 

@ScriptPup , is this related to the VS Code extensions for Teradata that you have created: https://github.com/ScriptPup/sqltools-teradata-driver ? I would love to connect with you. Could you please send me (adam.tworkiewicz@teradata.com) your contact info?

**Comment by adamtwo** [comment]
Please have a look at https://github.com/Teradata/nodejs-driver/pull/34 where I'm proposing a different solution to this problem. The solution in PR 34 follows the pattern described here: https://stackoverflow.com/questions/15176082/npm-package-json-os-specific-dependency. 

This PR is dependent on releasing a new version of `@teradataprebuilt/nativelib` so it won't work when you run it right now. Just to explain how it works:
1. A new version of `@teradataprebuilt/nativelib` will be os-dependent. For example, `@teradataprebuilt/nativelib-win32` will only load on Windows.
1. `nodejs-driver` will no longer modify the parent package.json. Instead,`nodejs-driver` will list all 3 `@teradataprebuilt/nativelib` libs as optional dependencies. Only one of the libs will load as the rest will fail the os test.
1. `nodejs-driver` will locate `@teradataprebuilt/nativelib` using `require.resolve()` call. That way, we are delegating how to locate the library to node.js. Also, this method ensures that we are loading the file from the project's `node_modules` directory not some arbitrary `node_modules` that happens to be mentioned first in `LD_LIBRARY_PATH`.

**Comment by rexsuecia** [comment]
@adamtwo I am good with any solution. But I think yours is better than mine :) 
Anything we can get out that is up to date and patched so that I do not have to maintain my own version would be great.

**Comment by adamtwo** [comment]
We have resolved this issue with https://github.com/Teradata/nodejs-driver/pull/34 so I'm closing this PR.

**Pull request closed without merging**
